version: 2
jobs:
    build:
        docker:
            - image: circleci/buildpack-deps:curl
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Build Elasticsearch versions
                command: |
                    - docker build -t quay.io/trackmaven/elasticsearch:1.7 1.7
                    - docker build -t quay.io/trackmaven/elasticsearch:2.1 2.1
            - run:
                name: Run tests
                command: |
                    - docker run -d --publish 9217:9200 --env ES_CLUSTER_NAME=hello --env ES_NODE_NAME=test --name=elasticsearch-1 quay.io/trackmaven/elasticsearch:1.7;
                    - docker run -d --publish 9212:9200 --env ES_NETWORK_BIND__HOST=0.0.0.0 --env ES_CLUSTER_NAME=hello --env ES_NODE_NAME=test --name=elasticsearch-2.1 quay.io/trackmaven/elasticsearch:2.1;
                    - sleep 20
                    - curl --fail -i http://localhost:9217
                    - curl --fail -i http://localhost:9212
